name: firs-workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Run a one-line script
              run: echo Hello, world!
            - name: list files
              run: ls -la
            - name: Readme file
              run: cat README.md

