name: generate-ascii artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Execute shell script to generate ASCII artwork
              run: |
                chmod +x .github/workflows/ascii-script..sh
                bash .github/workflows/ascii-script..sh
